FauxSuperheroSprint/FauxSuperheroSprint.UI/Controllers/CharactersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FauxSuperheroSprint.DATA.EF;

namespace FauxSuperheroSprint.UI.Controllers
{
    public class CharactersController : Controller
    {
        private SuperHeroesIncEntities db = new SuperHeroesIncEntities();

        // GET: Characters
        public ActionResult Index()
        {
            return View(db.Characters.ToList());
        }

        // GET: Characters/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Character character = db.Characters.Find(id);
            if (character == null)
            {
                return HttpNotFound();
            }
            return View(character);
        }

        // GET: Characters/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Characters/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "CharacterID,Name,Alias,Description,Occupation,IsHero,IsActive")] Character character)
        {
            if (ModelState.IsValid)
            {
                db.Characters.Add(character);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(character);
        }

        // GET: Characters/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Character character = db.Characters.Find(id);
            if (character == null)
            {
                return HttpNotFound();
            }
            return View(character);
        }

        // POST: Characters/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "CharacterID,Name,Alias,Description,Occupation,IsHero,IsActive")] Character character)
        {
            if (ModelState.IsValid)
            {
                db.Entry(character).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(character);
        }

        // GET: Characters/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Character character = db.Characters.Find(id);
            if (character == null)
            {
                return HttpNotFound();
            }
            return View(character);
        }

        // POST: Characters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Character character = db.Characters.Find(id);
            db.Characters.Remove(character);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FauxSuperheroSprint/FauxSuperheroSprint.UI/Controllers/CoursController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FauxSuperheroSprint.DATA.EF;

namespace FauxSuperheroSprint.UI.Controllers
{
    public class CoursController : Controller
    {
        private SuperHeroesIncEntities db = new SuperHeroesIncEntities();

        // GET: Cours
        public ActionResult Index()
        {
            return View(db.Courses.ToList());
        }

        // GET: Cours/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cours cours = db.Courses.Find(id);
            if (cours == null)
            {
                return HttpNotFound();
            }
            return View(cours);
        }

        // GET: Cours/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cours/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "CourseID,Name,Description")] Cours cours)
        {
            if (ModelState.IsValid)
            {
                db.Courses.Add(cours);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cours);
        }

        // GET: Cours/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cours cours = db.Courses.Find(id);
            if (cours == null)
            {
                return HttpNotFound();
            }
            return View(cours);
        }

        // POST: Cours/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "CourseID,Name,Description")] Cours cours)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cours).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cours);
        }

        // GET: Cours/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cours cours = db.Courses.Find(id);
            if (cours == null)
            {
                return HttpNotFound();
            }
            return View(cours);
        }

        // POST: Cours/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Cours cours = db.Courses.Find(id);
            db.Courses.Remove(cours);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FauxSuperheroSprint/FauxSuperheroSprint.UI/Controllers/CourseCharactersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FauxSuperheroSprint.DATA.EF;

namespace FauxSuperheroSprint.UI.Controllers
{
    public class CourseCharactersController : Controller
    {
        private SuperHeroesIncEntities db = new SuperHeroesIncEntities();

        // GET: CourseCharacters
        public ActionResult Index()
        {
            var courseCharacters = db.CourseCharacters.Include(c => c.Character).Include(c => c.Cours);
            return View(courseCharacters.ToList());
        }

        // GET: CourseCharacters/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CourseCharacter courseCharacter = db.CourseCharacters.Find(id);
            if (courseCharacter == null)
            {
                return HttpNotFound();
            }
            return View(courseCharacter);
        }

        // GET: CourseCharacters/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.CharacterID = new SelectList(db.Characters, "CharacterID", "Name");
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "Name");
            return View();
        }

        // POST: CourseCharacters/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "CourseCharacterID,CourseID,CharacterID")] CourseCharacter courseCharacter)
        {
            if (ModelState.IsValid)
            {
                db.CourseCharacters.Add(courseCharacter);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CharacterID = new SelectList(db.Characters, "CharacterID", "Name", courseCharacter.CharacterID);
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "Name", courseCharacter.CourseID);
            return View(courseCharacter);
        }

        // GET: CourseCharacters/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CourseCharacter courseCharacter = db.CourseCharacters.Find(id);
            if (courseCharacter == null)
            {
                return HttpNotFound();
            }
            ViewBag.CharacterID = new SelectList(db.Characters, "CharacterID", "Name", courseCharacter.CharacterID);
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "Name", courseCharacter.CourseID);
            return View(courseCharacter);
        }

        // POST: CourseCharacters/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "CourseCharacterID,CourseID,CharacterID")] CourseCharacter courseCharacter)
        {
            if (ModelState.IsValid)
            {
                db.Entry(courseCharacter).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CharacterID = new SelectList(db.Characters, "CharacterID", "Name", courseCharacter.CharacterID);
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "Name", courseCharacter.CourseID);
            return View(courseCharacter);
        }

        // GET: CourseCharacters/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CourseCharacter courseCharacter = db.CourseCharacters.Find(id);
            if (courseCharacter == null)
            {
                return HttpNotFound();
            }
            return View(courseCharacter);
        }

        // POST: CourseCharacters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            CourseCharacter courseCharacter = db.CourseCharacters.Find(id);
            db.CourseCharacters.Remove(courseCharacter);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FauxSuperheroSprint/FauxSuperheroSprint.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="Super Heroes, Inc., superheroes, citizen safety, drop crime rates, villains, making a difference" />
    <title>SuperHeros, Inc.</title>

    <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500italic,500,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <!-- Bootstrap -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <!-- FontAwesome -->
    <link rel="stylesheet" href="~/Content/font-awesome.min.css">
    <!-- MaterialCSS -->
    <link rel="stylesheet" href="~/Content/material.min.css">
    <!-- RipplesCSS -->
    <link rel="stylesheet" href="~/Content/ripples.min.css">

    <!-- ThemeCSS & Responsive CSS -->
    <link rel="stylesheet" href="~/Content/style.css">
    <link rel="stylesheet" href="~/Content/responsive.css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

    <header class="header">
        <div data-velocity="-.4" id="particles" class="header-bg"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="social-links">
                        <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-facebook"></i> <div class="ripple-wrapper"></div></a>
                        <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-twitter"></i> <div class="ripple-wrapper"></div></a>
                        <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-instagram"></i> <div class="ripple-wrapper"></div></a>
                        @*<a class="btn social-link" href="javascript:void(0)"><i class="fa fa-google-plus"></i> <div class="ripple-wrapper"></div></a>
                            <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-youtube"></i> <div class="ripple-wrapper"></div></a>
                            <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-linkedin"></i> <div class="ripple-wrapper"></div></a>*@
                    </div>
                </div>
            </div>
        </div>

        <div class="site-title-table">
            <div class="site-title-tablecell">
                <div class="slide-text">
                    <h2><a href="~/Home/Index"><span>S</span>uper<span>H</span>eros,<span>I</span>nc.</a></h2>
                    <p>Making an impact.</p>
                </div>
            </div>
        </div>
    </header>
    <section class="maincontent-wrap">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="maincotnent shadow-z-1">
                        <div class="mainmenu">
                            <div class="navbar navbar-nobg">
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                        <span class="sr-only">Toggle navigation</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                </div>
                                <ul>
                                    <li class="navbar-collapse collapse">
                                        <ul class="nav navbar-nav">
                                            <li class="active">@Html.ActionLink("Home", "Index", "Home")<div class="ripple-wrapper"></div></li>
                                            <li>@Html.ActionLink("About", "About", "Home")</li>
                                            <li>@Html.ActionLink("Courses", "Index", "Cours")</li>
                                            <li>@Html.ActionLink("Heroes/Villans", "Index", "Characters")</li>
                                            @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                                            {
                                                <li>@Html.ActionLink("Instructors", "Index", "CourseCharacters")</li>
                                            }
                                            <li><a href="~/Home/Contact">Contact</a></li>
                                            <li>@Html.Partial("_LoginPartial")</li>
                                            @*@if (!Request.IsAuthenticated)
                                                {
                                                <li>@Html.ActionLink("Register","Register","Account")</li>
                                                <li>@Html.ActionLink("Log In", "Login", "Account")</li>
                                                }*@
                                            @*@if (Request.IsAuthenticated)
                                                {
                                                }*@
                                            @*@if (Request.IsAuthenticated && User.IsInRole("Admin"))
                                                {
                                                    <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                                                    <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                                                }*@

                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    @RenderBody()
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="footer-bottom">
                        <div class="row">
                            <div class="col-md-8">
                                <div class="copyright-text">
                                    <p>© 2015 Avengers - All Rights Reserved. Coded with <i class="fa fa-heart"></i> by <a href="http://wpexpand.com" target="_blank">WP Expand</a></p>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="social-links footer-social-links">
                                    <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-facebook"></i> <div class="ripple-wrapper"></div></a>
                                    <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-twitter"></i> <div class="ripple-wrapper"></div></a>
                                    <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-instagram"></i> <div class="ripple-wrapper"></div></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="~/Scripts/jquery-1.11.2.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/material.min.js"></script>
    <script src="~/Scripts/ripples.min.js"></script>
    <script src="~/Scripts/jquery.scrolly.js"></script>
    <script src="~/Scripts/jquery.particleground.min.js"></script>
    <script src="~/Scripts/main.js"></script>
</body>
</html>

FauxSuperheroSprint/FauxSuperheroSprint.UI/Views/Shared/_OGLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>